<?php
/**
 * EmailTypeTemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire Email Service
 *
 * An email service
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmailTypeTemplateTest Class Doc Comment
 *
 * @category    Class */
// * @description EmailTypeTemplate
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailTypeTemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EmailTypeTemplate"
     */
    public function testEmailTypeTemplate()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {

    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {

    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {

    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {

    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "variables"
     */
    public function testPropertyVariables()
    {

    }

}
