<?php
/**
 * TemplatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire Simple Email Service
 *
 * A simple email service
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addNewContent
     *
     * .
     *
     */
    public function testAddNewContent()
    {

    }

    /**
     * Test case for addTemplate
     *
     * .
     *
     */
    public function testAddTemplate()
    {

    }

    /**
     * Test case for deleteContent
     *
     * .
     *
     */
    public function testDeleteContent()
    {

    }

    /**
     * Test case for deleteTemplate
     *
     * .
     *
     */
    public function testDeleteTemplate()
    {

    }

    /**
     * Test case for getContent
     *
     * .
     *
     */
    public function testGetContent()
    {

    }

    /**
     * Test case for getTemplate
     *
     * .
     *
     */
    public function testGetTemplate()
    {

    }

    /**
     * Test case for getTemplates
     *
     * .
     *
     */
    public function testGetTemplates()
    {

    }

    /**
     * Test case for updateContent
     *
     * Update Template Content.
     *
     */
    public function testUpdateContent()
    {

    }

    /**
     * Test case for updateTemplate
     *
     * .
     *
     */
    public function testUpdateTemplate()
    {

    }

}
